# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1526ddb2bb7e1e2bf9e679d3d9d5f6a66394ec362df2b3b95410ff3c690ddd018738179d41c7ad6c690c30619ce824298e555445f4cf8ad80818cdb68dea5c22

test:
  secret_key_base: 979ea33c171be744470c8719635ae713f2f07e0bc84c7debe717ac6c32d015cbbe1ecb64a46429580ef32657d0ee068d2e4ca5381c08aa1db9de680c3f3ac95e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
